openapi: 3.0.3
info:
  title: SGE-004 — Unidades Escolares
  version: 1.0.0
paths:
  /api/v1/unidades-escolares:
    get:
      summary: Lista paginada de unidades escolares
      parameters:
        - name: page
          in: query
          schema: { type: integer }
        - name: limit
          in: query
          schema: { type: integer }
        - name: q
          in: query
          schema: { type: string }
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        ueCodigo: { type: integer }
                        ueNome: { type: string }
                        munNome: { type: string }
                        ueStatus: { type: string }
